config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"
urlpatterns = [path("", room_views.Homeview.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

# Function based view
# urlpatterns = [path("<int:pk>", views.room_detail, name="detail")]

# Class based view
urlpatterns = [path("<int:pk>", views.RoomDetail.as_view(), name="detail"), path("search/", views.search, name="search")]

rooms/models.py
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from core import models as core_models
from users import models as user_models


class AbstractItem(core_models.TimeStampedModel):

    """Abstract Item class. Doesn't stay in the database."""

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):
    class Meta:
        verbose_name = "Room Type"


class Amenity(AbstractItem):
    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):
    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):
    class Meta:
        verbose_name = "House Rule"


class Room(core_models.TimeStampedModel):

    name = models.CharField(max_length=140, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    country = CountryField(null=True, blank=True)
    city = models.CharField(max_length=80, null=True, blank=True)
    price = models.IntegerField(null=True, blank=True)
    address = models.CharField(max_length=140, null=True, blank=True)
    beds = models.IntegerField(null=True, blank=True)
    bedrooms = models.IntegerField(null=True, blank=True)
    baths = models.IntegerField(null=True, blank=True)
    guests = models.IntegerField(null=True, blank=True)
    check_in = models.TimeField(null=True, blank=True)
    check_out = models.TimeField(null=True, blank=True)
    instant_book = models.BooleanField(default=False, null=True, blank=True)
    host = models.ForeignKey(
        user_models.User,
        related_name="rooms",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    roomtype = models.ForeignKey(
        RoomType,
        on_delete=models.SET_NULL,
        null=True,
    )
    amenities = models.ManyToManyField(Amenity, related_name="rooms")
    facilities = models.ManyToManyField(Facility, related_name="rooms")
    house_rules = models.ManyToManyField(HouseRule, related_name="rooms")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def total_avg(self):  # bringing review class objects for each room object
        reviews_all = self.reviews.all()
        reviews = 0
        for review in reviews_all:
            reviews += review.rating_avg()
        if len(reviews_all) > 0:
            return round(reviews / len(reviews_all), 2)
        else:
            return 0


class Photo(core_models.TimeStampedModel):

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey(
        Room, related_name="photos", on_delete=models.CASCADE
    )  # room -> photos, not photos -> room

    def __str__(self):
        return self.caption

rooms/forms.py
from django import forms
from django.db.models.constraints import CheckConstraint
from django.db.models.fields import CharField
from django.forms.widgets import CheckboxSelectMultiple
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

    city = forms.CharField(initial="Anywhere")
    price = forms.IntegerField(initial=False)
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        queryset=models.RoomType.objects.all(), required=False, empty_label="Any Kind"
    )
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelChoiceField(required=False, queryset=models.Amenity.objects.all(), widget=forms.CheckboxSelectMultiple)
    facilities = forms.ModelChoiceField(required=False, queryset=models.Facility.objects.all(), widget=forms.CheckboxSelectMultiple)

rooms/views.py
from django.views.generic import ListView, DetailView
from django.urls import reverse
from django.http import Http404
from django.shortcuts import render, redirect
from django_countries import countries
from . import models, forms
from django.core.paginator import Paginator


class Homeview(ListView):

    """Homeview model definition"""

    model = models.Room
    paginate_by = 10
    paginate_orphans = 5
    ordering = "name"
    page_kwarg = "page"
    template_name = "rooms/room_list.html"


# # Function based view
# def room_detail(request, pk):
#     try:
#         room = models.Room.objects.get(pk=pk)
#     except models.Room.DoesNotExist:
#         # return redirect(reverse("core:home"))
#         raise Http404()
#     return render(request, "rooms/detail.html", context={"room": room})


class RoomDetail(DetailView):
    model = models.Room
    template_name = "rooms/room_detail.html"


# values to be recevied from the form
# values to be sent to the form
# def search(request):
# city = request.GET.get("city", "Anywhere")
# city = str.capitalize(city)
# country = request.GET.get("country", "KR")
# room_type = int(request.GET.get("room_type", 0))
# room_types = models.RoomType.objects.all()
# amenities = models.Amenity.objects.all()
# facilities = models.Facility.objects.all()

# guests = request.GET.get("guests", "0")  ## error!
# # print("geee", guests)  # why return None?
# # print(type(guests))
# # print(guests)
# bedrooms = int(request.GET.get("bedrooms", 0))
# beds = int(request.GET.get("beds", 0))
# price = int(request.GET.get("price", 0))
# baths = int(request.GET.get("baths", "0"))
# # print("baths", baths)

# instant_book = bool(request.GET.get("instant_book", False))
# superhost = bool(request.GET.get("superhost", False))

# selected_amenities = request.GET.getlist("amenities")
# selected_facilities = request.GET.getlist("facilities")

# print(selected_amenities)

# options = {
#     "countries": countries,
#     "room_types": room_types,
#     "amenities": amenities,
#     "facilities": facilities,
# }
# forms = {
#     "selected_city": city,
#     "selected_country": country,
#     "selected_room_type": room_type,
#     "price": price,
#     "guests": guests,
#     "bedrooms": bedrooms,
#     "beds": beds,
#     "baths": baths,
#     "instant_book": instant_book,
#     "superhost": superhost,
#     "selected_amenities": selected_amenities,
#     "selected_facilities": selected_facilities,
# }

# filter_args = {}

# if city != "Anywhere":  # exclude default
#     filter_args["city__startswith"] = city

# filter_args["country"] = country

# if room_type != 0:
#     filter_args["room_type__pk__exact"] = room_type  # room_type is a foreign key

# if price != 0:
#     filter_args["price__lte"] = price

# if guests != 0:
#     filter_args["price__gte"] = guests

# if bedrooms != 0:
#     filter_args["bedrooms__gte"] = bedrooms

# if beds != 0:
#     filter_args["beds__gte"] = beds

# if baths != 0:
#     filter_args["baths__gte"] = baths

# if instant_book is True:
#     filter_args["instant_book"] = True

# if superhost is True:
#     filter_args["host__superhost"] = True

# if len(selected_amenities) > 0:
#     for a in selected_amenities:
#         filter_args["amenities__pk"] = int(a)

# if len(selected_facilities) > 0:
#     for f in selected_facilities:
#         filter_args["facilities__pk"] = int(f)

# print(filter_args)

# rooms = models.Room.objects.filter(**filter_args)

# return render(
#     request,
#     "rooms/search.html",
#     context={**options, **forms, "rooms": rooms}
#     # context={"city": city, "countries": countries, "room_types": room_types},
# )


def search(request):

    country = request.GET.get("country")

    if country:

        form = forms.SearchForm(request.GET)  # Import all the input data

        if form.is_valid():

            city = form.cleaned_data("city")
            price = form.cleaned_data("price")
            country = form.cleaned_data("country")
            room_type = form.cleaned_data("room_type")
            guests = form.cleaned_data("guests")
            bedrooms = form.cleaned_data("bedrooms")
            beds = form.cleaned_data("beds")
            baths = form.cleaned_data("baths")
            instant_book = form.cleaned_data("instant_book")
            superhost = form.cleaned_data("superhost")
            amenities = form.cleaned_data("amenities")
            facilities = form.cleaned_data("facilities")

            filter_args = {}

            if city != "Anywhere":  # exclude default
                filter_args["city__startswith"] = city

            filter_args["country"] = country

            if room_type is not None:
                filter_args[
                    "room_type__exact"
                ] = room_type  # room_type is a foreign key

            if price is not None:
                filter_args["price__lte"] = price

            if guests is not None:
                filter_args["price__gte"] = guests

            if bedrooms is not None:
                filter_args["bedrooms__gte"] = bedrooms

            if beds is not None:
                filter_args["beds__gte"] = beds

            if baths is not None:
                filter_args["baths__gte"] = baths

            if instant_book is True:
                filter_args["instant_book"] = True

            if superhost is True:
                filter_args["host__superhost"] = True

            for a in amenities:
                filter_args["amenities"] = a

            for f in facilities:
                filter_args["facilities"] = f

            print(filter_args)

            qs = models.Room.objects.filter(**filter_args).order_by("created")

            paginator = Paginator(qs, 10, orphans=5)

            page = request.GET.get("page", 1)

            rooms = paginator.get_page(page)

            return render(
                request, "rooms/search.html", context={"form": form, "rooms": rooms}
            )

    else:
        form = forms.SearchForm()

    return render(request, "rooms/search.html", context={"form": form})

templates/rooms/home.html
{% extends "base.html" %}

{% block page_name %}
Home
{% endblock page_name %}

{% block content %}

{% for room in page_obj.object_list %}
<h1>{{room.name}} / ${{room.price}}</h1>
{% endfor %}

{% if page_obj.has_previous %}
<a href="?page={{page_obj.number|add:-1}}">Previous</a>
{% endif %}

<h5>page {{page_obj.number}} of {{page_obj.paginator.num_pages}} </h5>

{% if page_obj.has_next %}
<a href="?page={{page_obj.number|add:1}}">Next</a>
{% endif %}

{% endblock content %}

templates/rooms/room_detail.html
{% extends "base.html" %}

{% block page_title %}
{{room.name}}
{% endblock page_title %}

{% block content %}

<h2>Host name</h2>
{{room.host.username}}

<h2>Superhost?</h2>
{% if room.host.superhost %}
Superhost
{% else %}
Non-Superhost
{% endif %}


<h3>Amenities</h3>
<ul>
    {% for a in room.amenities.all %}
    <li> {{a}} </li>
    {% endfor %}

</ul>
<h3>Facilities</h3>
<ul>
    {% for a in room.facilities.all %}
    <li> {{a}} </li>
    {% endfor %}
</ul>
<h3>House Rules</h3>
<ul>
    {% for a in room.house_rules.all %}
    <li> {{a}} </li>
    {% endfor %}
</ul>


{% endblock content %}

templates/rooms/room_list.html
{% extends "base.html" %}

{% block page_title %}
Home
{% endblock page_title %}

{% block content %}

{% for room in page_obj.object_list %}
<h3>
    <!-- <a href="/rooms/{{room.pk}}">{{room.name}} / ${{room.price}}</a> -->
    <a href="{% url 'rooms:detail' room.pk %}">{{room.name}} / ${{room.price}}</a>

</h3>
{% endfor %}

{% if page_obj.has_previous %}
<a href=" ?page={{page_obj.number|add:-1}}">Previous</a>
{% endif %}

<h5>page {{page_obj.number}} of {{page_obj.paginator.num_pages}} </h5>

{% if page_obj.has_next %}
<a href="?page={{page_obj.number|add:1}}">Next</a>
{% endif %}

{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}

{% block page_title %}
Search
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<h2> Search </h2>
<form mehod="get" action="{% url 'rooms:search' %}">
    {{form.as_p}}
    <button>Search</button>
</form>

<h3>Results</h3>
    {% room in rooms %}
        <h3>{{room.name}}</h3>
    {% endfor %}
{% endblock content %}

templates/rooms/search_old.html
{% extends "base.html" %}

{% block page_title %}
Search
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<h2> Search </h2>
<form mehod="get" action="{% url 'rooms:search' %}">
    <div>
        <label for="city">City </label>
        <input value="selected_city" id="city" name="city" placeholder="Search by City" />
    </div>
    <div>
        <label for="country">Country </label>
        <select id="country" name="country">
            {% for country in countries %}
            <option value="{{country.code}}" {% if selected_country == country.code %} selected {% endif %}>
                {{country.name}} </option>
            {% endfor %}
        </select>
    </div>
    <div>
        <label for="room_types">room_types </label>
        <select id="room_types" name="room_types">
            <option value="0" {% if selected_room_type == "0" %} selected {% endif %}> Any kind </option>
            {% for room_type in room_types %}
            <option value="{{room_type.pk}}" {% if selected_room_type == room_type.pk %} selected {% endif %}>
                {{room_type.name}} </option>
            {% endfor %}
        </select>
    </div>
    <div>
        <label for="Guests">Guests </label>
        <input value="{{guests}}" type="number" id="guests" name="guests" placeholder="Guests" />
    </div>
    <div>
        <label for="price">Price </label>
        <input value="{{price}}" type="number" id="price" name="price" placeholder="Price" />
    </div>
    <div>
        <label for="bedrooms">Bedrooms </label>
        <input value="{{bedrooms}}" type="number" id="bedrooms" name="bedrooms" placeholder="Bedrooms" />
    </div>
    <div>
        <label for="beds">Beds </label>
        <input value="{{beds}}" type="number" id="beds" name="beds" placeholder="Beds" />
    </div>
    <div>
        <label for="baths">Baths </label>
        <input value="{{baths}}" type="number" id="baths" name="baths" placeholder="Baths" />
    </div>
    <div>
        <label for="instant_book">Instant booking only?</label>
        <input type="checkbox" id="instant_book" name="instant_book" {% if instant_book %} checked {% endif %}/>
    </div>
    <div>
        <label for="superhost">Super host only?</label>
        <input value="{{superhost}}" type="checkbox" id="superhost" name="superhost" {% if superhost %} checked {% endif %}/>
    </div>
    <div>
        <h3>Amenity</h3>
        <ul>
            {% for amenity in amenities %}
            <li>
                <label for="a_{{amenity.pk}}"> {{amenity.name}}</label>
                <input id="a_{{amenity.pk}}" type="checkbox" name="amenities" value={{amenity.pk}} {% if amenity.pk|slugify in selected_amenities %} checked {% endif %} />
            </li>
            {% endfor %}
        </ul>
        <h3>Facility</h3>
        <ul>
            {% for facility in facilities %}
            <li>
                <label for="a_{{facility.pk}}"> {{facility.name}}</label>
                <input id="a_{{facility.pk}}" type="checkbox" name="facilities" value="{{facility.pk}}" {% if facility.pk|slugify in selected_facilities %} checked {% endif %} />
            </li>
            {% endfor %}
        </ul>
    <button>Search</button>
</form>
{% endblock content %}